/**
 * Curated Pexels search queries for the 80-meal catalog.
 * Some meal titles don't search well on their own ("Match Day Porridge"
 * returns stadium photos), so each maps to a proven food-search query.
 * Keys must match catalog meal names exactly.
 */
export const mealImageQueryMap: Record<string, string> = {
  // Match Day
  "Match Day Porridge with Banana & Honey": "porridge banana honey bowl",
  "White Toast with Jam & Scrambled Eggs": "scrambled eggs toast jam breakfast",
  "Pancakes with Maple Syrup & Berries": "pancakes berries maple syrup stack",
  "Rice Pudding with Cinnamon": "rice pudding cinnamon bowl",
  "Bagel with Peanut Butter & Banana": "bagel peanut butter banana",
  "Chicken Pasta with Tomato Sauce": "chicken pasta tomato sauce plate",
  "Chicken & Rice with Steamed Veg": "chicken rice broccoli plate",
  "Tuna Pasta Bake": "tuna pasta bake cheese",
  "Turkey & Sweet Potato Mash": "turkey mince sweet potato mash plate",
  "Jacket Potato with Beans & Cheese": "baked potato beans cheese",
  "Banana & Energy Bar": "banana energy bar snack",
  "White Rice Cake with Honey": "rice cakes honey snack",
  "Jam Sandwich on White Bread": "jam sandwich white bread",
  "Post-Match Recovery Shake": "chocolate banana smoothie glass",
  "Orange Segments & Dates": "orange slices dates fruit plate",
  "Post-Match Chicken Stir-Fry with Noodles": "chicken stir fry noodles bowl",
  "Salmon with Rice & Spinach": "salmon fillet rice spinach plate",
  "Beef Bolognese with Spaghetti": "spaghetti bolognese meat sauce",
  "Chicken Burrito Bowl": "burrito bowl chicken rice beans",
  "Margherita Pizza with Side Salad": "margherita pizza salad plate",

  // Training Day
  "Overnight Oats with Berries & Seeds": "overnight oats berries jar",
  "Eggs on Toast with Avocado": "avocado toast fried egg",
  "Greek Yogurt Bowl with Granola & Honey": "yogurt granola honey bowl",
  "Breakfast Wrap with Egg & Cheese": "breakfast wrap egg cheese",
  "Porridge with PB & Apple": "porridge peanut butter apple bowl",
  "Smoothie Bowl": "smoothie bowl granola berries",
  "Chicken & Quinoa Power Bowl": "chicken quinoa avocado bowl",
  "Tuna & Rice Salad": "tuna rice salad bowl",
  "Turkey & Wholemeal Pasta": "turkey pasta wholemeal plate",
  "Chicken Fajita Wraps": "chicken fajita wraps peppers",
  "Lentil & Vegetable Soup with Bread": "lentil soup bread bowl",
  "Egg Fried Rice": "egg fried rice peas bowl",
  "Chicken Caesar Wrap": "chicken caesar wrap cut",
  "Banana & Milk Recovery Drink": "banana milk smoothie glass",
  "PB & Jam Sandwich": "peanut butter jelly sandwich",
  "Trail Mix & Apple": "trail mix nuts apple snack",
  "Yogurt with Honey & Oats": "yogurt honey oats bowl",
  "Toast with Cottage Cheese & Tomato": "cottage cheese toast tomato",
  "Chicken Curry with Rice": "chicken curry rice bowl",
  "Salmon Pasta with Pesto": "salmon pasta pesto plate",
  "Beef Stir-Fry with Rice": "beef stir fry rice vegetables",
  "Veggie Chilli with Rice": "vegetable chili rice bowl",
  "Chicken & Sweet Potato Traybake": "chicken sweet potato roasted tray",
  "Shakshuka with Bread": "shakshuka eggs tomato pan bread",
  "Prawn & Noodle Stir-Fry": "prawn noodle stir fry bowl",

  // Rest Day
  "Veggie Omelette": "vegetable omelette spinach mushroom",
  "Smoked Salmon on Rye Toast": "smoked salmon rye bread cream cheese",
  "Turkish Eggs (Çılbır)": "turkish eggs yogurt chili butter",
  "Berry & Nut Yogurt Bowl": "yogurt berries nuts bowl",
  "Cottage Cheese & Fruit Plate": "cottage cheese fruit plate",
  "Chicken & Avocado Salad": "chicken avocado salad green",
  "Mediterranean Tuna Salad": "tuna salad feta cucumber tomato",
  "Bean & Halloumi Wrap": "halloumi wrap beans spinach",
  "Egg & Vegetable Frittata": "vegetable frittata slice plate",
  "Chicken Soup with Bread": "chicken soup bowl bread",
  "Grilled Salmon with Roasted Vegetables": "grilled salmon roasted vegetables plate",
  "Turkey Meatballs with Couscous": "turkey meatballs couscous tomato",
  "Prawn & Avocado Rice Bowl": "prawn avocado rice bowl",
  "Stuffed Bell Peppers": "stuffed peppers rice cheese",
  "Mushroom & Spinach Pasta": "mushroom spinach pasta garlic",

  // Recovery Day
  "Blueberry Protein Pancakes": "blueberry pancakes yogurt stack",
  "Salmon & Egg Breakfast Plate": "smoked salmon scrambled eggs plate",
  "Cherry & Almond Overnight Oats": "overnight oats cherry almonds jar",
  "High-Protein Banana Smoothie": "banana smoothie tall glass",
  "Egg & Bean Breakfast Bowl": "eggs beans toast breakfast plate",
  "Chicken & Brown Rice Recovery Bowl": "chicken brown rice broccoli bowl",
  "Salmon & Sweet Potato Bowl": "salmon sweet potato spinach bowl",
  "Turkey & Avocado Sandwich": "turkey avocado sandwich wholemeal",
  "Chickpea & Spinach Curry": "chickpea spinach curry rice",
  "Tuna Melt on Rye": "tuna melt rye cheese",
  "Chocolate Milk": "chocolate milk glass",
  "Greek Yogurt with Walnuts & Honey": "greek yogurt walnuts honey bowl",
  "Rice Cakes with PB & Banana": "rice cakes peanut butter banana",
  "Fruit & Nut Mix with Dried Mango": "dried fruit nuts mango mix",
  "Cottage Cheese on Cracker with Cucumber": "cottage cheese crackers cucumber",
  "Baked Salmon with Quinoa & Greens": "baked salmon quinoa spinach plate",
  "Chicken & Vegetable Pasta Bake": "chicken pasta bake cheese",
  "Beef & Broccoli with Noodles": "beef broccoli noodles asian",
  "Mackerel on Toast with Salad": "mackerel toast salad plate",
  "Lentil Bolognese with Pasta": "lentil bolognese pasta bowl",
};
